project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!publications/_template/"


website:
  title: "safenlp.org"
  site-url: "https://safenlp.org"
  repo-url: "https://github.com/safenlp/safenlp.github.io"
  favicon: images/favicon.drawio.png
  google-analytics: "UA-177339812-1"
  twitter-card: true
  #back-to-top-navigation: true
  page-navigation: false
  search: true
  page-footer: 
    background: "#F6F5F3"
    center: © 2024  &middot; Made with {{< fa brands r-project >}} and 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) 
    right:
      - icon: github
        href: https://github.com/MasielloGroup/MasielloGroupWebsite
  
  navbar:
    search: true
    title: false
    logo: images/logo.drawio.png
    background: "#F6F5F3"
    logo-alt: "SafeNLP.org"
    left:
      - href: blog/index.qmd
        text: blog
      - href: publications/index.qmd
      - href: codes/index.qmd
        text: Codes
      - href: events/index.qmd
        text: "Key Talks & Events"
      - href: contact.qmd
        text: Contact

  sidebar:
    - id: empty-to-suppress-sidebars-on-other-pages


format:
  html:
    theme: 
      - styles/custom.scss
      - yeti
    mainfont: Nunito Sans
    toc: true
    link-external-newwindow: true
    date-format: "MMM YYYY"
    smooth-scroll: true
    resources:
      - images



